function Get-NIC26GeneratedHeader {
    <#
    .SYNOPSIS
        Returns the standard header lines (as an array of strings without comment markers) for generated files.
    #>
    [CmdletBinding()]
    [OutputType([string[]])]
    param(
        [Parameter(Mandatory)]
        [string]$Tool,

        [Parameter(Mandatory)]
        [string]$SolutionName
    )

    return @(
        "GENERATED by NIC26.Automation $Tool at $([DateTime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ssZ')) from solution '$SolutionName' (solution.yml)."
        'Do not edit and do not commit: *.generated.* is git-ignored (automation/.gitignore). Re-run the converter instead.'
        'Contains only the inputs declared in solution.yml plus the resolved names catalog. Secrets appear only as keyvault:// references.'
    )
}
